---
title: "Publications"
---

<!-- #### Submitted/under review -->


#### 2023

Shahmohammadi, S., **Seemann, H.**, Stede, M., & Scheffler, T. (2023). Encoding discourse
structure: comparison of RST and QUD. In M. Strube, C. Braud, C. Hardmeier, J. J. Li, S.
Loáiciga, & A. Zeldes (Eds.), Proceedings of the 4th Workshop on Computational Approaches to
Discourse (CODI 2023) (Publisher’s Version). Assoc. for Computational Linguistics.
https://aclanthology.org/2023.codi-1.11/

Scheffler, T., Kern, L.-A., & **Seemann, H.** (2023). Individuelle linguistische Variabilität in sozialen Medien: ein multimediales Korpus. In M. Kupietz (Ed.), Neue Entwicklungen in der Korpuslandschaft der Germanistik (Publisher’s Version, Vol. 11, pp. 87–97). Gunter Narr Verlag. [PDF](https://elibrary.narr.digital/content/chapter/10.24053/9783823396024_10.pdf)


#### 2022

**Seemann, H.**, & Scheffler, T. (2022). Differentiating Social Media Texts via Clustering. In F.
Karsdrop, A. Lassche & K. Nielbo (Ed.), Proceedings of the Computational Humanities Research
Conference 2022. https://ceur-ws.org/Vol-3290/

Scheffler, T., Kern, L.-A. & **Seemann, H.** (2022). The medium is not the message. Register
Studies. https://doi.org/10.1075/rs.22009.sch






